### ISSUE TITLE
Crash at the new version

### ISSUE THREAD

**Issue by UnEnanoMas** [fuyutsuki/Texter#101] opened 2020-11-28 13:59 UTC
**Describe the bug**
Crash the server

**To Reproduce**
Just upload the texter

**Expected behavior**
Crash the server x2

**Screenshots**
Not important for a crash

**Server (please complete the following information):**
 - OS: Windows 10
 - PMMP: 3.16.0
 - Plugins: Texter, Devtools and more

**Additional context**
```bash
[13:54:52] [Server thread/INFO]: Loading Texter v3.4.11
[13:54:52] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'Core' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/Texter-master/src/tokyo/pmmp/Texter/Core" at line 48
[13:54:52] [Server thread/CRITICAL]: #0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[22] tokyo\pmmp\Texter\Core)
[13:54:52] [Server thread/CRITICAL]: #1 (): BaseClassLoader->{closure}(string[22] tokyo\pmmp\Texter\Core)
[13:54:52] [Server thread/CRITICAL]: #2 (): spl_autoload_call(string[22] tokyo\pmmp\Texter\Core)
[13:54:52] [Server thread/CRITICAL]: #3 src/pocketmine/plugin/PluginManager(167): class_exists(string[22] tokyo\pmmp\Texter\Core, boolean 1)
[13:54:52] [Server thread/CRITICAL]: #4 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[37] /home/container/plugins/Texter-master, array[1])
[13:54:52] [Server thread/CRITICAL]: #5 plugins/PocketMine-DevTools.phar/src/DevTools/DevTools(69): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, array[1])
[13:54:52] [Server thread/CRITICAL]: #6 src/pocketmine/plugin/PluginBase(116): DevTools\DevTools->onEnable()
[13:54:52] [Server thread/CRITICAL]: #7 src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
[13:54:52] [Server thread/CRITICAL]: #8 src/pocketmine/Server(1787): pocketmine\plugin\PluginManager->enablePlugin(object DevTools\DevTools)
[13:54:52] [Server thread/CRITICAL]: #9 src/pocketmine/Server(1773): pocketmine\Server->enablePlugin(object DevTools\DevTools)
[13:54:52] [Server thread/CRITICAL]: #10 src/pocketmine/Server(1532): pocketmine\Server->enablePlugins(integer 0)
[13:54:52] [Server thread/CRITICAL]: #11 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
[13:54:52] [Server thread/CRITICAL]: #12 src/pocketmine/PocketMine(304): pocketmine\server()
[13:54:52] [Server thread/CRITICAL]: #13 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)
```

**Comment by fuyutsuki** [comment] 2020-11-29 02:18
Duplicate of #97, #98 and #99

**Closed by fuyutsuki** 2020-11-29 02:18 UTC
Labels: Duplicate, Status: Reproduced
