### ISSUE TITLE
floating texts with /txt a doesnt work.

### ISSUE THREAD

**Issue by HonorGamerHD** [fuyutsuki/Texter#28] opened 2018-06-28 09:49 UTC
### 必須項目 (Required items)

* ServerOS: Win10Home (Altay Turanic Pro)

* PHP version: 7.2 (64bit?)

* Minecraft version: MCPE 1.4.4 (android device)

* Texter version: latest poggit version

* issue(s): when i use /txt a the ui will shown and when i press on send nothing happens, in config files there arent my floating text and on the world isnt a floating text. please fix.

**Comment by fuyutsuki** [comment] 2018-06-28 10:20
Could you show me your `plugins` folder?

**Comment by HGHD-Developer** [comment] 2018-06-28 10:21
yes wait

**Comment by HGHD-Developer** [comment] 2018-06-28 10:29
11:29:21 INFO > Plugins (31): Broadcast-ZT v2, BanGUI v1.0.0, BanSystem-ZT v2, CombinedSlots v1.0.0, MysteryCrate v6.0.0, CustomBenachrichtigung v2, DoubleJump v1.0.1, essentialsTP v1.2.0-8, FormAPI v1.1.1, GuiShop v1.0.0-BETA1, Implactor vIR-1.2.6.1, LobbyItems-ZT v1, MOTDShuffle-ZT v2, MultiWorld v1.4.3, PlayerSize v2, Report-ZT v1, AlwaysSpawn v2.2.4, BlockPets v1.1.2, BoostPad v1.1, BuilderTools v1.1.0-beta1, Cameraman v1.1.1, PurePerms v1.4.2, SignEdit v1.2.3, Slapper v1.4.0, Texter v2.4.1, WelcomeMessage v1.0.0, Worlds v2.0.3, SlapBack v1.0.1, SlapperCache v2.0.0, SlapperCooldown v1.0.0, PureChat v1.4.11

**Comment by HGHD-Developer** [comment] 2018-06-28 10:30
custom benachrichtigung is an edit of custom alterts

**Comment by fuyutsuki** [comment] 2018-06-28 10:51
Texter.phar was downloaded from poggit?

**Comment by HGHD-Developer** [comment] 2018-06-28 10:52
yes

**Comment by HGHD-Developer** [comment] 2018-06-28 10:54
![firefox_screenshot_2018-06-28t10-53-37 790z](https://user-images.githubusercontent.com/37555011/42030200-4cddfe4a-7ad2-11e8-864a-ffd5517c7b53.png)

this

**Comment by fuyutsuki** [comment] 2018-06-28 13:03
I will investigate. Please let me know if you notice anything else.

**Comment by fuyutsuki** [comment] 2018-06-29 22:36
forgotten update libform XD

**Comment by fuyutsuki** [comment] 2018-06-30 06:45
Dear @HGHD-Developer.  
I couldn't reproduce this issue. Please try reinstalling the plugin as follows.  
1. Remove plugins/Texter-dev**.phar
2. Remove plugin_data/Texter folder
3. Redownload from poggit

**Comment by HGHD-Developer** [comment] 2018-07-07 19:52
Okay, i test it tomorrow

**Comment by fuyutsuki** [comment] 2018-08-03 16:31
It has been a while since the report, so this issue is closed as there is no reply.  
If the issue still continues, please reopen this.

**Closed by fuyutsuki** 2018-08-03 16:31 UTC
Labels: Status: Unreproduced
