### ISSUE TITLE
I'm facing this issue while starting the server with this plugin, it crashes the server

### ISSUE THREAD

**Issue by NwiZiyanoW** [fuyutsuki/Texter#99] opened 2020-11-26 15:06 UTC
[20:27:08] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'Core' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)" (EXCEPTION) in "plugins/Texter_3.4.11.phar/src/tokyo/pmmp/Texter/Core" at line 48
[20:27:08] [Server thread/CRITICAL]: #0 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[22] tokyo\pmmp\Texter\Core)
[20:27:08] [Server thread/CRITICAL]: #1 (): BaseClassLoader->{closure}(string[22] tokyo\pmmp\Texter\Core)
[20:27:08] [Server thread/CRITICAL]: #2 (): spl_autoload_call(string[22] tokyo\pmmp\Texter\Core)
[20:27:08] [Server thread/CRITICAL]: #3 src/pocketmine/plugin/PluginManager(167): class_exists(string[22] tokyo\pmmp\Texter\Core, boolean 1)
[20:27:08] [Server thread/CRITICAL]: #4 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[67] C:\Users\Nrimanta\Desktop\Minecraft\plugins\Texter_3.4.11.phar, array[2])
[20:27:08] [Server thread/CRITICAL]: #5 src/pocketmine/Server(1531): pocketmine\plugin\PluginManager->loadPlugins(string[49] C:\Users\Nrimanta\Desktop\Minecraft\plugins\)
[20:27:08] [Server thread/CRITICAL]: #6 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[41] C:\Users\Nrimanta\Desktop\Minecraft\, string[49] C:\Users\Nrimanta\Desktop\Minecraft\plugins\)
[20:27:08] [Server thread/CRITICAL]: #7 src/pocketmine/PocketMine(304): pocketmine\server()
[20:27:08] [Server thread/CRITICAL]: #8 (11): require(string[96] phar://C:/Users/Nrimanta/Desktop/Minecraft/PocketMine-MP.phar/src/pocketmin)

**Comment by fuyutsuki** [comment] 2020-11-26 16:13
Duplicate of #97 and #98

**Closed by fuyutsuki** 2020-11-26 16:13 UTC
