### ISSUE TITLE
Text Disappearing Bug

### ISSUE THREAD

**Issue by SleakGaming1** [fuyutsuki/Texter#159] opened 2024-03-09 15:39 UTC
**Describe the bug**
Hello. When I have text, it disappears after around a minute. I am unsure why this happens.

**Expected behavior**
When I add floating text, it should stay until I remove it.

**Server (please complete the following information):**
 - PMMP: 5.12.0
 - Plugins: Texter

**Comment by fuyutsuki** [comment] 2024-03-13 18:25
Hi @SleakGaming1,
I have identified the problem and will investigate and correct the cause!

**Comment by fuyutsuki** [comment] 2024-03-13 19:18
Fixed in [4.3.1](https://github.com/fuyutsuki/Texter/releases/tag/v4.3.1(fecd04e)). Thank you for your report!

**Closed by fuyutsuki** 2024-03-13 19:18 UTC
Labels: Status: Reproduced

**Comment by SleakGaming1** [comment] 2024-03-16 20:49
> Fixed in [4.3.1](https://github.com/fuyutsuki/Texter/releases/tag/v4.3.1(fecd04e)). Thank you for your report!

This issue is still occurring for me. I have updated to the latest version of Texter & Pocketmine-MP.
